var GAME_LEVELS = [
   ["                                                                           ",
   "                                                                           ",
   "                                                    oo   oo   o  oo    oo  ",
   "         xx  x  x   x    xx  xx xxx  xxx x x  xx   o    o  o  o  o o  o    ",
   "        x   x x x   x   x   x    x    x  x x x     o    o  o  o  o o   oo  ",
   "        x   x x x   x   xxx x    x    x  xxx xxx   o    o  o  o  o o     o ",
   "        x   x x x   x   x   x    x    x  x x x      oo   oo   o  o o   oo  ",
   "   @     xx  x  xxx xxx  xx  xx  x    x  x x  xx         xxxxxxxxx         ",
   "                                                                       xxx ",
   " xxx                                                                   x x ",
   " x x                                                                   x x ",
   " x xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx x ",
   " x                                                                       x ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "                                                                           ",
   "                                                                           "],

   ["                                                                           ",
   "                                                                           ",
   "                                                                           ",
   "                                                                           ",
   "                                                                           ",
   "                                                                           ",
   "                      u   u   u                           o            o   ",
   "                      x   x   x                           o            o   ",
   "                      x o x o x                                            ",
   "                 xxxxxxxxxxxxxxxxx                       xxx        xxxxxxx",
   "                 x               x                                   x     ",
   "               xxx        xxxxxxxx                                   x     ",
   "                 x        xoo   dd                xxx          xxx   x     ",
   "       xxx       x        xoo                                        x     ",
   "                 x        xoo                            ooo         x     ",
   "                 x        xooG               xx          xxx         x     ",
   "  @            xxx        xxxxxxxxxxxxxxxxxxxxx                      x     ",
   "                Gx                           x!!!!!!!!!!!!!!!!!!!!!!!x     ",
   "xxxxxxxxxxxxxxxxxx                           x!!!!!!!!!!!!!!!!!!!!!!!x     ",
   "                                             xxxxxxxxxxxxxxxxxxxxxxxxx     ",
   "                                                                           "],

  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                 dddddddddddddxx",
   "xx                    xxxxxxxxxxxxxxxxxxxxxxxxxxxx                          6   xx",
   "xx                    ddddxxxxxxxxxxxxxxxxxxxxxxxx                              xx",
   "xx  @     o   o   o       xxxxxxxxxxxxxxxd d d 6             xxxxxx             xx",
   "xx                        xxxxxxxxxxxxxxx o o          xxxxxxxxxxxxxxxxxxx      xx",
   "xx            uu          xxxxxxxxxxxxxxx o o                          xx       xx",
   "xxxxxxxxxxxxxxxxxxxx      ddddxxxxxxxxxxx o o                          xx       xx",
   "xxxxxxxxxxxxxxxxxxxx          xxxxxxxxxxx o o                          xx       xx",
   "xxxxxxxxxxxxxxxxxxxx          xxxxxxxxxxxxxxxxxxxxx                    xx      oxx",
   "xxxxxxxxxxxxxxxxxxxx          xxxxxxxxxxxxxxxxxxxxx                    xx    xxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxx      xxxxxxxxxxxxxxxxxxxxx      o             xx      dxx",
   "xxxxxxxxxxxxxxxxxxxxxxxx      xxxxxxxxxxxxxxxxxxxxx    xxxxx           xx       xx",
   "xxxxxxxxxxxxxxxxxxxxxxxx      xxxxxxxxxxxxxxxxxxxxx    ddddd           xx       xx",
   "xxxxxxxxxxxxxxxxxxxxxxxx      xxxxxxxxxxxxxxxxxxxxd                    xxo      xx",
   "xxxxxxxxxxxxxxxxxxxxxxxx      xxxxxxxxxxxxxxxxxxxd                 o   xxxxx    xx",
   "xxxxxxxxxxxxxxxxxxxxxxxx      xxxxxxxxxxxxxxxxxxd                xxxxx xxd      xx",
   "xxxxxxxxxxxxxxxxxxxxxxxx      xxxxxxxxxxxxxxxxxd                 ddddd xx       xx",
   "xxxxxxxxxxxxxxxxxxxxxxxx     oxxxxxxxxxxxxxxxxd                        xx       xx",
   "xxxxxxxxxxxxxxxxxxxxxxxx      xxxxxxxxxxxxxxxd           o             xx       xx",
   "xxxxxxxxxxxxxxxxxxxxxxxx     oxxxxxxxxxx               xxxxx           xx      oxx",
   "xxxxxxxxxxxxxxxxxxxxxxxx      xxxxxxxxxx               ddddd           xx    xxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxx     oxxxxxxxx                                 xx      dxx",
   "xxxxxxxxxxxxxxxxxxxxxxxx      xxxxxxx          o                       xx       xx",
   "xxxxxxxxxxxxxxxxxxxxxxxx                     xxxxx                     xx      oxx",
   "xxxxxxxxxxxxxxxxxxxxxxxx G             xx    ddddd                     xx      oxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                              xxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"], 
   
   ["                                  x                                                     ",
   "                                   x                                                    ",
   "                                   x                                                    ",
   "                                   x                                                    ",
   "                        o       @  x                                                    ",
   "                       xxxxxxxxxxxxx                                                    ",
   "                                                                                        ",
   "                                                                                        ",
   "          o                                                             o               ",
   "         xxx                                                           xxx              ",
   "   o      d      o                                               o      d      o        ",
   "  xxx           xxx                                             xxx           xxx       ",
   "   d      o      d                                               d      o      d        ",
   "          x                                                             x               ",
   "   o             o               oo                              o             o        ",
   "  xxx           xxx              xx                             xxx           xxx       ",
   "   d      o      d              xxxx                             d      o      d        ",
   "         xxx                   xx  xx                                  xxx              ",
   "          d           xxxxxxxxxx    xxxxxxxxxxxxxxx     xxxxxxxxxx      d               ",
   "                      x                                          x                      ",
   "                      x          o   o                           x                      ",
   "                      x                   x                      x  x                   ",
   "                      x                   x                      x  x                   ",
   "                      x        xxxxxxxxx  x                      x  x                   ",
   "                      x                x  xxxx!!!!!!!!!!!!!!!!xxxx  x                   ",
   "                      x                x    xx!!!!!!!!!!!!!!!!xx    x                   ",
   "                      x                xx    x!!!!!!!!!!!!!!!!x    xx                   ",
   "                      x                xxxx  x!!!!!!!!!!!!!!!!x  xxxx                   ",
   "                      x                   x  xxxxx!!!!!!!!xxxxx  x  x                   ",
   "                      xo                  x     xx!!!!!!!!xx     x  x                   ",
   "                      xoo                 xx     x!!!!!!!!x     xx  x                   ",
   "                      xxxxxxxx            xxxxx  x!!xxxx!!x  xxxxx  x                   ",
   "                             x                x  x!!x  x!!x  x      x                   ",
   "                             x                x  xxxxooxxxx  x      x                   ",
   "                             x                x      oo      x      x                   ",
   "                             x                xx G          xx      x                   ",
   "                             xo               xxxxxxxxxxxxxxxx      x                   ",
   "                             xoo                 |                  x                   ",
   "                             xxxxxx                |              o x                   ",
   "                                  x                   |           o x                   ",
   "                                  x    G x               |   6 x  o x                   ",
   "                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                   ",
   "                                                                                        ",
   "                                                                                        ",
   "                                                                                        ",
   "                                                                                        ",
   "                                                                                        "],

  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                  xxx           ",
   "                                                   xx      xx    xx!xx          ",
   "                                    o o      xx                  x!!!x          ",
   "                                                                 xx!xx          ",
   "                                   xxxxx                          xvx           ",
   "                                                                            xx  ",
   "  xx                                      o o                                x  ",
   "  x                     o                                                    x  ",
   "  x                                      xxxxx                             o x  ",
   "  x          xxxx       o                                                    x  ",
   "  x  @       x  x                                                xxxxx       x  ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxx  ",
   "                              x   x                  x     x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                      x!!x                        xxxxxxx                                    x!x  ",
   "                                      x!!x                     xxxx     xxxx                                 x!x  ",
   "                                      x!!xxxxxxxxxx           xx           xx                                x!x  ",
   "                                      xx!!!!!!!!!!xx         xx             xx                               x!x  ",
   "                                       xxxxxxxxxx!!x         x                                    o   o   o  x!x  ",
   "                                                xx!x         x     o   o                                    xx!x  ",
   "                                                 x!x         x                                xxxxxxxxxxxxxxx!!x  ",
   "                                                 xvx         x     x   x                        !!!!!!!!!!!!!!xx  ",
   "                                                             xx  |   |   |  xx            xxxxxxxxxxxxxxxxxxxxx   ",
   "                                                              xx!!!!!!!!!!!xx            v                        ",
   "                                                               xxxx!!!!!xxxx                                      ",
   "                                               x     x            xxxxxxx        xxx         xxx                  ",
   "                                               x     x                           x x         x x                  ",
   "                                               x     x                             x         x                    ",
   "                                               x     x                             xx        x                    ",
   "                                               xx    x                             x         x                    ",
   "                                               x     x      o  o     x   x         x         x                    ",
   "               xxxxxxx        xxx   xxx        x     x               x   x         x         x                    ",
   "              xx     xx         x   x          x     x     xxxxxx    x   x   xxxxxxxxx       x                    ",
   "             xx       xx        x o x          x    xx               x   x   x               x                    ",
   "     @       x         x        x   x          x     x               x   x   x               x                    ",
   "    xxx      x         x        x   x          x     x               x   xxxxx   xxxxxx      x                    ",
   "    x x      x         x       xx o xx         x     x               x     o     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x     =     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxxx xx  o o  xx                    ",
   "!!!!x x!!!!!!x         x!!!!!x    o                 xx!!!!!!xx !                    xx     xx                     ",
   "!!!!x x!!!!!!x         x!!!!!x                     xx!!!!!!xx  !                     xxxxxxx                      ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        o                                                                     ",
   "                                                                                                              ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                       xxx                                                                    ",
   "                                       x x                 !!!        !!!  xxx                                ",
   "                                       x x                 !x!        !x!                                     ",
   "                                     xxx xxx                x          x                                      ",
   "                                      x   x                 x   oooo   x       xxx                            ",
   "                                      x   x                 x          x      x!!!x                           ",
   "                                      x   x                 xxxxxxxxxxxx       xxx                            ",
   "                                     xx   xx      x   x      x                                                ",
   "                                      x   xxxxxxxxx   xxxxxxxx              x x                               ",
   "                                      x   x           x                    x!!!x                              ",
   "                                      x   x           x                     xxx                               ",
   "                                     xx   xx          x                                                       ",
   "                                      x   x= = = =    x            xxx                                        ",
   "                                      x   x           x           x!!!x                                       ",
   "                                      x   x    = = = =x     o      xxx       xxx                              ",
   "                                     xx   xx          x                     x!!!x                             ",
   "                              o   o   x   x           x     x                xxv        xxx                   ",
   "                                      x   x           x              x                 x!!!x                  ",
   "                             xxx xxx xxx xxx     o o  x!!!!!!!!!!!!!!x                   vx                   ",
   "                             x xxx x x xxx x          x!!!!!!!!!!!!!!x                                        ",
   "                             x             x   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "                             xx           xx                                         xxx                      ",
   "  xxx                         x     x     x                                         x!!!x                xxx  ",
   "  x x                         x    xxx    x                                          xxx                 x x  ",
   "  x                           x    xxx    xxxxxxx                        xxxxx                             x  ",
   "  x                           x           x                              x   x                             x  ",
   "  x                           xx          x                              x x x                             x  ",
   "  x                                       x       |xxxx|    |xxxx|     xxx xxx                             x  ",
   "  x                xxx             o o    x                              x         xxx                     x  ",
   "  x               xxxxx       xx          x                             xxx       x!!!x          x         x  ",
   "  x               oxxxo       x    xxx    x                             x x        xxx          xxx        x  ",
   "  x                xxx        xxxxxxxxxxxxx  x oo x    x oo x    x oo  xx xx                    xxx        x  ",
   "  x      @          x         x           x!!x    x!!!!x    x!!!!x    xx   xx                    x         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o oxxx x       ",
   "                   xxx                                                                                x       ",
   "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]

];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
